spring.application.name=Resilience4jTask
server.port=8080



# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.deliveryService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.deliveryService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.deliveryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.deliveryService.waitDurationInOpenState=5000
