spring.application.name=EurekaConsumerRestaurant
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.com.feignclient=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

